#!/bin/sh

# user-defined pre-exec hook
test -r "${XDG_CONFIG_HOME:-$HOME/.config}"/pinentry/preexec &&
    . "${XDG_CONFIG_HOME:-$HOME/.config}"/pinentry/preexec

# site-defined pre-exec hook
test -r /etc/pinentry/preexec &&
    . /etc/pinentry/preexec

# Use pinentry-curses if $PINENTRY_USER_DATA contains USE_TTY=1
echo $PINENTRY_USER_DATA | grep -q USE_TTY=1 &&
    exec /usr/bin/pinentry-curses "$@"

# check for Qt dependencies
test -e /usr/lib/libQt6Core.so.6 &&
    exec /usr/bin/pinentry-qt "$@"


# check for GTK dependencies
test -e /usr/lib/libgtk-x11-2.0.so.0 &&
    exec /usr/bin/pinentry-gtk-2 "$@"


exec /usr/bin/pinentry-curses "$@"
