# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your neeeds...
precmd () { echo -n "\x1b]1337;CurrentDir=$(pwd)\x07" }


unsetopt SHARE_HISTORY
setopt INC_APPEND_HISTORY_TIME

export TERM=xterm-256color
export LC_COLLATE=zh_CN.utf8
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

path+=("$HOME/.cargo/bin" "$HOME/.local/bin")

ld_library_path+=('')

alias ll='ls -AlFhi --group-directories-first'
alias tmux='tmux -u'
alias upgrade='sudo bash -c "apt update && apt upgrade -y && apt autoremove --purge -y && apt autoclean -y"'
alias watch='watch -c -d'


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# bun completions
[ -s "/home/ethan/.bun/_bun" ] && source "/home/ethan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

if [ -f /usr/local/bin/weed ]; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C /usr/local/bin/weed weed
fi
